### ISSUE TITLE
Allow parameters to be created from file and/or command line

### ISSUE THREAD

**Issue by pvdvreede** [realestate-com-au/stackup#16]
It would be cool if I could specify a parameters file and also set some parameters on the command line eg. `stackup mystack up -t template -p paramsfile -p buildnumber=1`.

This way I could change something like the version or build number from the command line and keep all other items in the params file. Currently I need to use sed and a placeholder in the params file to change this.

**Comment by mdub** [comment]
@pvdvreede would you want parameters on the command-line to override those in the params file?

I think it might be confusing to overload `-p`, so would prefer a different option for command-line overrides.  How about `--override`, or `-o`?

**Comment by pvdvreede** [comment]
Yeah, I would think the cli parameters override the file parameters, so `-o` sounds good to me :+1:
