### ISSUE TITLE
Take template from stdin

### ISSUE THREAD

**Issue by pvdvreede** [realestate-com-au/stackup#17]
Is it possible to provide your json template via standard in eg, `cfndsl myrubycfntemplate.rb | stackup mystack up -p params_file`.

This would be really handy if you use a tool like cfndsl, cfoo, troposphere etc and dont want to have to have an intermediary step of writing the json to a file.

**Comment by mdub** [comment]
Would bash process substitution be sufficient?  Something like:

```
stackup mystack up -t <(cfndsl myrubycfntemplate.rb) -p params.json
```

**Comment by pvdvreede** [comment]
Didnt know about that! Yeah that sounds like it would be fine.
