### ISSUE TITLE
Named IAM role capabilities

### ISSUE THREAD

**Issue by aidansteele** [realestate-com-au/stackup#28]
[`lib/stackup/stack.rb#L129`](lib/stackup/stack.rb#L129) has the line:

```ruby
options[:capabilities] ||= ["CAPABILITY_IAM"]
```

There's a new capability named `CAPABILITY_NAMED_IAM`, but there appears to be no way to use it with stackup. It would be great if this was added to the defaults (as above) or some way to specify capabilities was provided.

**Comment by mdub** [comment]
To clarify, are you talking about the `stackup` CLI?

For programmatic usage, you can try specifying a `:capabilities` option.

But yeah, it does sound worth adding this to the default set of capabilities.

**Comment by mdub** [comment]
My reading (of [the CloudFormation documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#using-iam-capabilities)) suggests that `CAPABILITY_NAMED_IAM` is a superset of `CAPABILITY_IAM`, and therefore:

```ruby
options[:capabilities] ||= ["CAPABILITY_NAMED_IAM"]
```

should suffice.  Do you concur, @aidansteele?
