### ISSUE TITLE
Needs Ruby 2.1+

### ISSUE THREAD

**Issue by aidansteele** [realestate-com-au/stackup#34]
In [`lib/stackup/yaml.rb#L27`](https://github.com/realestate-com-au/stackup/blob/master/lib/stackup/yaml.rb#L27), there is the line:

```ruby
CloudFormationToRuby.create.accept(tree)
```

`Psych::Visitors::ToRuby::create` appears to have been introduced in the YAML library bundled with Ruby 2.1.x. It fails with a `NoMethodError` on earlier Rubies.

This probably isn't a problem on account of the earlier Rubies being EOL'd, but Ruby 2.0.0 is bundled with even the latest macOS, so perhaps a note in the README is warranted? Or I could submit a PR with a hack to check whether the method exists, otherwise fall back to `::new`. Your call 👍

**Comment by mdub** [comment]
Hmm. Nice find. I should probably get the tests running on older Rubies.

I would gladly accept a PR.
