### ISSUE TITLE
Multi-OS Docker image

### ISSUE THREAD

**Issue by aidansteele** [realestate-com-au/stackup#38]
G'day @mdub,

I've found myself in the unfortunate position where I occasionally have to run `stackup` from a _Windows_ host. Ruby is quite the pain on Windows and I've got an uphill fight if I want to convince coworkers to go through that pain to enjoy the bliss that is `stackup`.

How amenable would you be to a PR that adds multi-OS support to the Docker images for `stackup`? Now with Docker supporting both Linux and Windows containers (but not both at the same time without massive pain), it would be nice if users could just `docker run -it stackup` regardless of which mode is currently active. I'd be happy to do the work, just want to know if you'd accept something like that spoiling this otherwise wonderful repo.

**Comment by mdub** [comment]
Hey @aidansteele. I sympathise with your plight.

On the face of it, I'm all for supporting Windows too, and would happily accept a PR. 

On the other hand, I'm worried by your use of the word "spoiling".  I've not Docker'ed on Windows: is it hard/bad? How would this affect my release process?

**Comment by aidansteele** [comment]
Docker for Windows isn't _too_ bad and I might have got carried away with the term _spoiling_. I'm just used to being a macOS/Linux guy and not having to deal with The Other Operating System. 

It depends on how you currently do your releases. I see in the `.travis.yml` file that it's just doing Ruby stuff, not pushing any images to Docker Hub. Are the Docker images manually created right now on your end?

**Comment by mdub** [comment]
Yes, I release from my laptop (running Docker for Mac).  But I'm open to letting Travis do the releases.

**Comment by aidansteele** [comment]
Hm, Travis doesn't do Windows :( Lemme think about it a bit more..

**Comment by aidansteele** [comment]
https://docs.docker.com/docker-hub/builds/ 

Maybe the Docker Hub "automated builds" functionality could do it for us. I don't immediately see anything saying it doesn't support Windows. Will give it a try and report back 👍

**Comment by mdub** [comment]
Closing due to lack of action.
