### ISSUE TITLE
!Sub not substituting pseudovariables in YAML CFN templates 

### ISSUE THREAD

**Issue by benhutchison** [realestate-com-au/stackup#40]
See YAML [template](https://git.realestate.com.au/consumer-data/test-data-lambdas/blob/master/deploy/sns-invoke-lambda.yml#L7) that uses !Sub to substitute pseudo parameters.

Output observed in [build](https://buildkite.com/rea/test-data-lambdas/builds/33#bdb98e7b-c753-4c03-a852-915ab4dfb863/24-222) implies substitution not performed.
```
INFO: [15:41:10] SnsPermissionAddBuyProfile - UPDATE_FAILED - 2 validation errors detected: Value 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*' at 'sourceArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:([a-zA-Z0-9\-])+:([a-z]{2}-[a-z]+-\d{1})?:(\d{12})?:(.*); Value 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:*' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?
```

**Comment by mdub** [comment]
Out of interest, does the same template work when you use the AWS CLI, Ben?

**Comment by benhutchison** [comment]
Yes it does. 

It was surprisingly hard (for me at least) to verify this, because the AWS console shows the yaml stack with pseudo-params unsubstituted, but this was my methodology:

Starting state: no stack in the AWS account. Slightly redacted.
```
$ aws sns list-subscriptions | grep -3 function:addBuyProfile
<nothing>
$ aws cloudformation create-stack --stack-name test-data-sns-invoke-lambda-stack2 \
  --template-body file://deploy/sns-invoke-lambda.yml
{
    "StackId": "arn:aws:cloudformation:ap-southeast-2:40xxxxxxxx01:stack/test-data-sns-invoke-lambda-stack2/xxxxxxxxxxxxxx"
}
$ aws sns list-subscriptions | grep -3 function:addBuyProfile
        {
            "Owner": "40xxxxxxxx01",
            "Endpoint": "arn:aws:lambda:ap-southeast-2:40xxxxxxxx01:function:addBuyProfile",
            "Protocol": "lambda",
            "TopicArn": "arn:aws:sns:ap-southeast-2:40xxxxxxxx01:cbr-profiler",
            "SubscriptionArn": "arn:aws:sns:ap-southeast-2:40xxxxxxxx01:cbr-profiler:70xxxxxx-xxxx-xxxx-xxxx-5d18195b4d47"
```

You can see the

**Comment by mdub** [comment]
I've not been able to reproduce this problem (yet).  What version of `stackup` are you using, @benhutchison?  Are you using the gem version, or the Docker image?

Support for the AWS YAML extensions was added in stackup 1.0.0.

**Comment by benhutchison** [comment]
Right, the build in question was using stackup `0.9.5` so thats probably the explanation. Closing, will reopen if I can find a counter example.
