### ISSUE TITLE
Can remote parameters files be accessed?

### ISSUE THREAD

**Issue by andrewoh531** [realestate-com-au/stackup#42]
Documentation says so `You can use either local files, or HTTP URLs, to specify inputs; stack template, parameters, etc.` but when I attempt to access a parameters file from s3 I get the following error:

`ERROR: cannot read "https://s3-ap-southeast-2.amazonaws.com/my-bucket-12345/dev-parameters.yml" - 403 Forbidden`

**Comment by mdub** [comment]
Yes, you should be able to use remote URLs for parameters. They need to be world-readable, though.

Are you able to download your parameters file using `curl`, or a web-browser, @andrewoh531?

**Comment by andrewoh531** [comment]
Oh right. No it's not public. Could it pull from a private bucket? Similar to this?

https://github.com/realestate-com-au/stackup/issues/37

**Comment by mdub** [comment]
> Could it pull from a private bucket?

I'm afraid not. Pulling templates from private buckets is possible, because the [UpdateStack](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html) API call supports a `TemplateURL` parameter. Similarly for `StackPolicyURL`.  But there's no `ParametersURL`.
