### ISSUE TITLE
Please document required IAM permissions for `up` command

### ISSUE THREAD

**Issue by benhutchison** [realestate-com-au/stackup#50]
I'm porting a build onto stackup and are discovering one by one the IAM permissions that stackup's `up` command requires.

                "cloudformation:CreateStack",
                "cloudformation:UpdateStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",

Would be good to mention these (and any others Ive yet to discover) in the docs around credentials.

**Comment by Dombo** [comment]
Out of interest what approach are you using to grant the appropriate permissions required for a stack update?

* Do you have a generic set of permissions that you extend per stack/logical unit?
* Do you have an admin role that you let your CI assume?
* Do you scope with tags & conditions?

Keen to hear a way I can manage this with a reasonable tradeoff between speed of development & principle of least privilege.
