### ISSUE TITLE
Templates over 51kb in size should use S3

### ISSUE THREAD

**Issue by TJC** [realestate-com-au/stackup#56]
Attempting to create stacks with templates over 51kb (after JSON conversion) result in errors from the AWS API.

Instead, these templates need to be uploaded to an S3 bucket, and then a pre-signed URL passed to cloudformation with the `template-url` parameter, rather than `template-body`.

**Comment by katherinelim** [comment]
Have you tried referencing the template as a URL in S3? Support was added recently: https://github.com/realestate-com-au/stackup#using-urls-as-inputs

**Comment by TJC** [comment]
No, I hadn't tried that. (Although I am using the S3 URL feature with the aws cli already)

I'll look into it. Thanks.

**Comment by shaun-whitely** [comment]
Hi @TJC. How did you go with specifying an S3 url to `stackup`?

**Comment by TJC** [comment]
Thanks for the reminder. Sorry, I haven't actually tried that out, as the plain aws-cli method was working OK and I moved onto something else.

I'd prefer using stackup, so I'll try and get back to it.

**Comment by TJC** [comment]
Using the URL as the template parameter works fine.
