### ISSUE TITLE
allow CAPABILITY_NAMED_IAM through the cli

### ISSUE THREAD

**Issue by samjeffress** [realestate-com-au/stackup#69]
Hi, 

I can see that you can set a `capability` through using the ruby code, but I'm using stackup as a cli tool, and would like to be able to pass CAPABILITY_NAMED_IAM as a parameter which at the moment I'm unable to do. 

There was discussion on #28 but it doesn't look like it's resulted in any changes. 

Thanks

Sam

**Comment by TheTaylorHicks** [comment]
Hi all. I'm going to close this issue as it has hopefully been addressed in in release 1.4.3 and https://github.com/realestate-com-au/stackup/pull/75.

Please reopen if the above PR does not completely address the issue.
