### ISSUE TITLE
Mismatch between env variable in readme file and what stackup expects

### ISSUE THREAD

**Issue by tamirrrdorrron** [realestate-com-au/stackup#95]
In the readme there is a reference to an env variable to handle the `--retry-limit` behaviour. That env variable in the readme is `$AWS_RETRY_LIMIT` where stackup expects `$AWS_API_RETRY_LIMIT`.

readme: https://github.com/realestate-com-au/stackup/blob/fd18e6102d37eaa031b1a45e1a4ae85c9307147f/README.md?plain=1#L73

stackup: https://github.com/realestate-com-au/stackup/blob/main/lib/stackup/main_command.rb#L34

I noticed this because I was specifying the env variable and wasn't getting the expected result (ie it doesn't throw an error so it's a bit of a silent error)

**Comment by tigris** [comment]
Thanks. Fixed in https://github.com/realestate-com-au/stackup/commit/6da7dd74e636c9a1f1b7cf715f5c48ffbb167a3d
